n = input()
line = list(map(int, input().split()))

minimum = min(line)
maximum = max(line)
count = line.index(maximum)
print(count, line)
line.pop(count)
print(line)
line.insert(0, count)
print(line)
line.reverse()
print(line)
count += line.index(minimum)
print(count)